### ISSUE TITLE
Firebase Item Monitor bug.

### ISSUE THREAD

**Issue by El3mancer** [Chadori/construct-master-collection#134]
## Request Type
This is a **Bug Report**.

## Describe the bug
Firebase item monitor cannot use.

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
Create new project.
Add firebase, firebase api, firebase item monitor.
Run preview.
Black screen.
errors appear in console.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
latest . R164.3 Stable.

 ## Construct 2 Version
 **The Construct 2 Version**

**Comment by Chadori** [comment]
Will be fixed as soon as possible, thanks for reporting.

**Comment by Chadori** [comment]
Hi, it seems that I can't reproduce the issue with the Firebase API credentials defined in the properties section. 

I think you haven't filed that yet, maybe a reproducible project sent to me privately can help on the [Discord Server](https://discordapp.com/invite/eS3HK88) might help. Thanks.

Test results, console:
![image](https://user-images.githubusercontent.com/31282960/65913282-2dbded00-e402-11e9-9e1a-8ac242c94d41.png)

Will close it for now, you can make a new issue and reference this one if you have any more concerns.

**Comment by Chadori** [comment]
Also, in case of related or other Firebase issues, I don't use the Firebase Master Collection on my own projects anymore, so if anyone can present a reproducible project, even through private message or email.
**I would be glad to prioritize its repair, since I'm not sure if it's high-quality anymore, since I haven't used it for months now.**

Thanks.
