### ISSUE TITLE
Firebase Auth is notworking on Android

### ISSUE THREAD

**Issue by vundurty** [Chadori/construct-master-collection#164]
## Request Type
This is a **Bug Report**.

I'm not sure whether it is a bug but I'm sure this should not be working in this way. Please correct me if I'm missing anything to make it work.

## Describe the bug
In android, the Firebase auth doesn't work. It throws below error 
![WhatsApp Image 2019-10-20 at 9 46 44 PM](https://user-images.githubusercontent.com/22640025/67162669-d5846600-f383-11e9-80ea-cb27397efa79.jpeg)

I'm sure I setup the initialization properly. It is working fine with web.
![Screenshot 2019-10-20 21 47 28](https://user-images.githubusercontent.com/22640025/67162691-0cf31280-f384-11e9-91a4-ecdf6ddd2198.png)

I tired with both popup and redirect methods
![Screenshot 2019-10-20 21 53 55](https://user-images.githubusercontent.com/22640025/67162718-665b4180-f384-11e9-8129-9201dcabd582.png)

I have defined them as global variables and initialized in the primary layout.
![Screenshot 2019-10-20 21 58 48](https://user-images.githubusercontent.com/22640025/67162798-509a4c00-f385-11e9-9ca8-fcb9718cf371.png)

I set the Firebase apps

![Screenshot 2019-10-20 22 04 13](https://user-images.githubusercontent.com/22640025/67162841-cef6ee00-f385-11e9-9c46-e97d988f2214.png)

![Screenshot 2019-10-20 22 06 26](https://user-images.githubusercontent.com/22640025/67162856-fc439c00-f385-11e9-8659-9d85df856d2b.png)

Not sure whether it is going wrong. Please help.

## Expected behavior
Login should happen

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **R173.3 Stable**

## Additional Info
Please let me know if you need any further information.

Thanks in advance.

**Comment by Chadori** [comment]
Unfortunately, you might have not seen my announcement before, but Google dropped support for **Firebase Web** on **Android** and **iOS**, it's ideal for **Web** and **Mobile Web** only.

I encourage using the **PlayFab Master Collection** more for both **Android** and **iOS**, since it supports **native authentication** with the **Mobile Facebook**, **Mobile Google Plus**, **Mobile Apple SignIn** and **other auth methods**, to avoid issues like this.

Webview Firebase Authentication is **not supported anymore**, the **Firebase Master Collection** isn't equipped to handle mobile from the start, although it does work with the **Mobile Browser**, since it wasn't restricted. But now, after the drop, it's no longer viable.

Hence, why I've created the **PlayFab Master Collection** + **Mobile Authentication** addons.

------

Although, it might still work in basic situations. I haven't used Firebase in a long time, after the drop, so I can't say for sure, but I'll try to help.

## Possible solution

The alert said, the working environment isn't secure, you might have not yet **white-listed** the **localhost** from the **Firebase Console**.
This is a workaround, since **Firebase Web** is supposedly only for **secure websites**, while a native mobile app is a **local application**. So, it's kind of a trick, which is what the others are doing when using the **Firebase Master Collection** on mobile, which I discourage. But, it does work.

Remember that **Construct 3 Preview** uses a **secure server** (https), but once you have exported to mobile, or if you are using the Construct 2 preview. You will no longer be in a secure environment, hence will be run on local (http).
Which seems to be the reason.

I hope that fixes your problem.

## If it doesn't work

Export your project as a debug .apk and follow the instructions here:
https://www.constructcollection.com/construct-mobile-intro
Under **Mobile Built-in Debugger** and get me the console log, a screenshot.

**Comment by vundurty** [comment]
Truely I was not aware of this update. 

I will use PlayFab as per your suggestion.

I'm closing this thread.
