### ISSUE TITLE
app id is missing or empty [Appsflyer] iOS

### ISSUE THREAD

**Issue by Boulerzzz** [Chadori/construct-master-collection#300]
## Request Type
This is a **Bug Report**.

## Describe the bug
When implementing Appsflyer in a IOS app the Appsflyer SDK won't initialize. It throws an "app id is missing or empty" error even though the app id is provided with the initialize action.

## Steps to Reproduce
1.  Add Appsflyer to your app.
2.  Fill in the Dev key and App ID in the initialize action.
3.  Build the app and launch.
4.  The SDK won't initialize because "app id is missing or empty"

## Expected behavior
To initialize so that events and app launches can be monitored in Appsflyer.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **r210.2**

**Comment by Chadori** [comment]
I can see the fault in the addon. Thanks for reporting.

**Comment by Chadori** [comment]
**Self Note:**
`domSide.js` post must be `appId` instead of `appID`.

**Comment by Chadori** [comment]
**Mobile AppsFlyer - 1.0.1.1** - Initialization in iOS fails due to the invalid `appId` custom-post reference in the `domSide.js`.
The release should be available in the [Discord Community's](https://discordapp.com/invite/eS3HK88) `#next-release` channel, kindly download there the update until the next version is published.

Thank you.
