### ISSUE TITLE
IronSource+AppLovin - ads stop showing on Android

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#331]
## Request Type
This is a **Bug Report**.

## Describe the bug
As discussed on Discord - 
After a few successful interstitial/rewarded ads are displayed, further ads are not showing on Android.
The following error can be seen in Logcat:
_ironSourceSDK: API: showInterstitial error: can't show ad while an ad is already showing_
So it seems like IronSource does not receive 'completed' event from the previous ad and gets stuck.

## Events set up

![image](https://user-images.githubusercontent.com/36763350/97771140-0352dc00-1b8e-11eb-9218-985546c6d7c1.png)

## Additional info

1. Interstitial ad is shown after finishing each level, only one "Show interstitial" request is made at a time. 
Rewarded video is shown when user taps a button.
I performed these tests myself, so a situation when previous ad is still playing and another ad is requested is not possible.

2. There are several ad networks in the project, but this seems to happen only after an AppLovin ad has finished.
This doesn't happen if we remove AppLovin plugin from the project. However, AppLovin is the most profitable network, so it is critical for us to find a solution/fix to this issue.. 

3. In my tests, this problem occurs after a mix of several successful interstitial+rewarded ads.
For example: Interstitial, Interstitial, Rewarded, Interstitial - next Interstitial fails..

## Logs
https://www.dropbox.com/s/pxpqr2phd8z8gsg/logs.zip?dl=0
I enabled Debug Mode on IronSource plugin when recording these logs.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r218

**Comment by Chadori** [comment]
Thanks for the detailed information.
I'll try to make a fix soon. I recall this is urgent, do you have a specific date when you need this?
I'll have to schedule this, I'm afraid.

**Comment by Chadori** [comment]
Thanks for the detailed information. This significantly helps a lot!
I'll try to make a fix soon. I recall this is urgent, do you have a specific date when you need this?
I'll have to schedule this, I'm afraid.

**Comment by dop2000** [comment]
I guess the answer is as soon as possible. We are in the middle of a ROI test and losing score without AppLovin network.. So it would be great if it can be fixed in the next few days. 
Thanks!

**Comment by Chadori** [comment]
Oh, it's that urgent. Alright, I'll try today.

**Comment by Chadori** [comment]
Hi, 
I've updated the **AppLovin SDK** to the later version where they have fixed the issue but not so far to cause any breaking changes to our current IronSource SDK version and other ad-network SDK versions. 

![image](https://user-images.githubusercontent.com/31282960/97785529-8ef55880-1be0-11eb-8766-098751624d66.png)

When an update is recommended, I usually update the entire collection to avoid compatibility issues. The current IronSource SDK version we are using is quite stable and I hope to not update it yet until it's necessary, since it's quite time consuming to rewrite.
Fortunately, the AppLovin issue is an isolated case, and therefore now fixed. 

Thank you for the detailed report, it's significantly faster to fix things this way.
Let me know if you still have other ad-networks that are having issues, although kindly make another bug report for it since this one will be closed.

## Solution

Kindly replace `chadori-mobile-ironsource-applovin@0.0.3` to `chadori-mobile-ironsource-applovin@0.0.4`.
It should now work. 

Good luck with your project!
