### ISSUE TITLE
IronSource+Admob issues on iOS

### ISSUE THREAD

**Issue by dop2000** [Chadori/construct-master-collection#332]
## Request Type
This is a **Bug Report**.

## Describe the bug

We receive multiple reports from users that interstitial ads sometimes get stuck on the screen. 
In our tests we were able to reproduce this bug a couple of times and every time this was an ad from Google.

Another issue we noticed with Admob ads is that they often close by itself after 1-2 seconds. It looks like the video inside the ad starts loading and then crashes.

## Log
https://www.dropbox.com/s/emub3hgx573dgp4/ios-admob-issue.txt?dl=0

Search for "show interstitial", which happened at 11:54:07.199804

Please note, that to reproduce this bug we had to remove all other ad plugins from the project, so there may be a lot of errors about missing adapters.
Also, we had to use VPN to mock location in the US, because otherwise Admob ads were not served.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
r218

## Additional Info

Can this be a similar issue to #331 with AppLovin? I see that Admob SDK is 6 versions old, could you please try updating it?

This bug has the same severity as #331

**Comment by Chadori** [comment]
Hi, thank you.

This looks like an IronSource SDK issue with loading ad-networks, which was just recently fixed.
I have now updated the IronSource SDK to its latest version.

The Admob SDK is actually  not 6 versions down, it's quite new, it was just updated this September 2020, for iOS 14. I didn't update it again to lessen the risks of compatibility issues, since a recommended approach is to update the entire collection's SDK together.

Due to time constraints, I only update the entire collection's SDK version on every major and stable update.

However, the main goal is to fix the issue and fortunately it should now be.

## Solution
Kindly change `chadori-mobile-ironsource@0.0.4` to `chadori-mobile-ironsource@0.0.5`.
Debugging version: `chadori-mobile-ironsource-debug@0.0.4` to `chadori-mobile-ironsource-debug@0.0.5`.

## Other Notes

Let me know if there are still other ad-networks having issues or if the current update broke the previously working ad-networks. 
Also, kindly report it on a separate issue thread, since this will be closed. Thanks.

**Comment by Chadori** [comment]
**[Self note]** Conflicts with ad-networks, requires entire collection rewrite for the new versions.

**Comment by Chadori** [comment]
The full **IronSource SDK** update including all of its **ad-network mediation SDKs**, are now completed, and is currently in testing.
For further updates, please refer to https://github.com/Chadori/Construct-Master-Collection/issues/337, this is the thread of the new incoming update.
