### ISSUE TITLE
Minification error with just the PLayFab api addon and HTML export

### ISSUE THREAD

**Issue by rhg1968** [Chadori/construct-master-collection#376]
## Request Type
This is a **Bug Report**.

## Describe the bug
If I create a test project with only the playfab api addon and try to export as an HTML project with advanced minification, the app won't run and shows the following error:

Uncaught (in promise) TypeError: self.C3_CreateRuntime is not a function
    at b.qb (main.js:18)
    at async b.Da (main.js:11)

## Reproducible .c3p or .capx
[Test.zip](https://github.com/Chadori/Construct-Master-Collection/files/5869658/Test.zip)

## Steps to Reproduce
1. Open project 
2. Export as html with advanced minification
3. Run as a web site.
4. It will fail to come up and error will be shown in the console

## Expected behavior
The main screen of the game should come up

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **r232**

 ## Construct 2 Version
 **The Construct 2 Version**

## Additional Info
Using version 11.0 of addons

**Comment by Chadori** [comment]
Hi,
Thank you for reporting. 
However, all the requirements for `advanced minification` has already been duly implemented.

I think this is like one of those Construct 3 bug issues that are internal that we have to wait out until the Addon SDK for module and minifier support stabilizes.
We have a similar case with the [Photon addons](https://github.com/Chadori/Construct-Master-Collection/issues/355) not working with both the minifier and preview due to the new JS Modules support, but after a few releases it started working again, without our intervention.

In any case, I'll remain this opened until it is resolved. You can still use the `Simple` minifier until then.

**Comment by Chadori** [comment]
Note: The requirements for `advanced minification` seems to be duly implemented, otherwise it wouldn't compile with the advanced minifier. This error seems to only happen after launching the application, suggesting it is a runtime error instead.

**Comment by Chadori** [comment]
A new [Construct 3 update](https://www.construct.net/en/make-games/releases/beta/r233) `(r233)` arrived and it seems to explain this issue and its solution.
If no further issues are encountered, then this should be fixed in the next coming release.
Thank you.

**Comment by Chadori** [comment]
Thanks, it's now fixed!
You can get the update in advance from the [#next-release](https://discordapp.com/invite/eS3HK88) channel.

![image](https://user-images.githubusercontent.com/31282960/105880096-e8352280-603d-11eb-8c0d-37749a4aba49.png)

**PlayFab API :: 4.2.1.6** - Fixed hidden minification errors, helped solved by [Construct 3 r233](https://www.construct.net/en/make-games/releases/beta/r233)'s new minifier debugger.

**Comment by Chadori** [comment]
![image](https://user-images.githubusercontent.com/31282960/105881331-5201fc00-603f-11eb-9eff-9c66a53e487a.png)

**Comment by Chadori** [comment]
Running exported applications work fine now as well.
