### ISSUE TITLE
iOS - CFBundleURLSchemes variables not filled properly in exported XCode file

### ISSUE THREAD

**Issue by neosaberleo** [Chadori/construct-master-collection#544]
## Request Type
This is a **Bug Report**.

## Describe the bug
An issue with the MobileFacebook plugin, but it's only a problem for iOS. After exporting as an XCode file, the CFBundleURLSchemes variables (in the info.plist file) are erroneously filled.

***(MobileFacebook settings in Contruct 3)***
![2022-06-03 04_24_28-Bubble Defence - Construct 3 - Brave](https://user-images.githubusercontent.com/49565208/172004581-533d06dd-b891-421b-b210-655e62118045.png)

***("CFBundleURLSchemes" entries in info.plist file)***
![2022-06-03 04_25_29-F__!!!!!FanFlare_!!!Bubble Defence_Game Export_iOS_Bubble Defence-Info plist - N](https://user-images.githubusercontent.com/49565208/172004595-ab727fb5-ce9d-48a3-b2b8-761132da524e.png)

This causes issues when trying to build and archive in XCode, and the CFBundleURLSchemes variables have to be manually edited, before the build and archive can work.

## Reproducible .c3p or .capx
[Mobile Facebook (c3p).zip](https://github.com/Chadori/Construct-Master-Collection/files/8837977/Mobile.Facebook.c3p.zip)

## Steps to Reproduce
Steps to reproduce the behaviour:
1. Open the demo project
2. Select the Mobile Facebook plugin and fill in the "App ID" and "App Name" fields. Leave the rest as is.
3. Export the project as iOS (Cordova), but ensure "Xcode" is selected on the next screen and not "Cordova"
4. Once exported, navigate to the info.plist file and open the file in a text editor.
5. Look for the entries under "CFBundleURLSchemes". The entries should be filled properly

## Expected behaviour
The entries under "CFBundleURLSchemes" in the info.plist file should be filled properly, and should not cause any error when trying to build and archive the project in XCode.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
Release R293.3 stable

 ## Construct 2 Version
N/A

**Comment by Chadori** [comment]
Unfortunately, this seems to be a combination of a limitation of the Construct 3 Build Service and the hooks script of the Cordova plugin getting conflicted with the editor on export, causing this issue.

There is no way to solve this without overcomplicating the situation, however there is a workaround. 

I instead created a separate branch of the Construct 3 plugin where the properties `Other App Schemes` and `URL Scheme Suffix` aren't included for projects that do not utilize the features, which would consequently no longer create those incorrectly appended configuration property values.

For those who utilize the feature, populating the properties should resolve the issue. If not, it would still be worth editing afterwards since you do utilize the feature. Also, chances are developers rarely would use the aforementioned features, it is only included just in case someone does use those advanced features.

This is the best workaround I could provide for now, though I think this might change in the future. I hope that helps.

The update with the fix should be available in the next release.
