### ISSUE TITLE
Mobile Browser  does not work when the web worker is enabled

### ISSUE THREAD

**Issue by XIMIKATIK** [Chadori/construct-master-collection#558]
## Request Type
Mobile Browser  does not work when the web worker is enabled

## Describe the bug
When enabling a web worker in a project and exporting to android, the plugin stops working
https://drive.google.com/file/d/1z8Q8fTw_GM9xq3HClk6Unhi8Rkp5acFw/view?usp=sharing

## Reproducible .c3p or .capx
_Insert the project file here._

## Steps to Reproduce
1. 
2. 
3. 
4. 

## Construct Editor
 - Construct 2
 - Construct 3

## Construct Runtime
 - Construct 2
 - Construct 3

 ## Construct 3 Version 
 **The Construct 3 Version**

 ## Construct 2 Version
 **The Construct 2 Version**

**Comment by Chadori** [comment]
I've once started development to support worker mode for Android, and have already implemented to most plugins when support was announced. However, considering there are performance issues where even Construct 3 disabled worker mode internally by default and warned against it, I halted its development for the remaining plugins which includes the Mobile Browser.

I think the time spent would be more productive to allocate for other features if there would be no benefit in supporting worker mode for Android. And even iOS doesn't have support for worker mode yet.

Any reasons why you would want to use worker mode for Android?

**Comment by Chadori** [comment]
I would be very interested to support worker mode, considering it is for performance purposes. However, contrary to its purpose there have been issues with it that degrades performance instead.

**Comment by XIMIKATIK** [comment]
@Chadori Strange, I didn't know that the working mode slows down the work of games created on construct 3. When testing on Samsung s10, games with working mode show excellent performance, maybe it depends on the devices? This is the future, however, I would like to see support for the working mode in all your plugins, although I understand that it probably takes a lot of time.

**Comment by Chadori** [comment]
The Android worker mode performance issue is still ongoing, for reference:

![image](https://user-images.githubusercontent.com/31282960/184022754-df8f4b39-9348-49a2-9703-17e68aaca5db.png)

There are still no changes to this issue as there are still no announcements of the issue being resolved. However, I will add support for this in the to-do list if it helps knowing in comfort that this option exists regardless. Fortunately, only a few plugins are left without support since most plugins were already ported when worker mode support for Android was announced, and new plugins inherently supports worker mode by design.

Please beware though that your application is still susceptible to performance issues with worker mode set to `Yes` instead of the recommended option `Auto`. Meaning worker mode is not enabled by default by Construct 3 while a performance issue is still being investigated. 

iOS also automatically disables worker mode due to lack of platform support.

For more information about the experimental API, [click here](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas).

**Comment by Chadori** [comment]
I'll start with Mobile Browser first so you can build immediately.

**Comment by XIMIKATIK** [comment]
@Chadori Thank you for clarifying everything. I just couldn't figure out for a long time why it didn't work, because I thought that all your plugins supported the working mode, and the android application worked without errors in the console for this plugin, unlike other plugin manufacturers, when the plugin did not support the working mode, the application simply did not start and ended with an error.

**Comment by Chadori** [comment]
Please refer here for the progress: https://github.com/Chadori/Construct-Master-Collection/issues/563

**Comment by Chadori** [comment]
Completed worker mode support on Android for the **Mobile Browser** plugin with version `4.4.0.0`.

Please refer to the [Discord Server](https://discord.com/invite/eS3HK88) in the `#next-release` channel if you would like to get the update earlier. The channel is accessible for those who already have the **supporter** role. If you do not have the supporter role, please kindly read the instructions in the public `#introduction` channel.

Thank you.
