### ISSUE TITLE
[Mobile Notification] Small icon is displayed as square when replacing default construct's icons to custom

### ISSUE THREAD

**Issue by ArtemLanin** [Chadori/construct-master-collection#613]
## Request Type
This is a **Bug Report**.

## Describe the bug
When replace default icons to custom, they are displayed as a square in push notifications

## Reproducible .c3p or .capx
[push_with_custom_icons.zip](https://github.com/Chadori/Construct-Master-Collection/files/11360101/push_with_custom_icons.zip)

## Steps to Reproduce
1. Install Mobile Notification
2. Build the project with custom icons
3. Run it and click to get push
4. Wait 1 min
5. Check small icon on push notification

## Expected behavior
Should be a custom icon but it's displayed as a square

## Screenshots
![image](https://user-images.githubusercontent.com/79050161/235324947-e6cff09f-e173-47c0-80c4-90dae69f9d35.png)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
CONSTRUCT 3 R336

**Comment by Chadori** [comment]
It's not a bug, it's probably just your theme. The effect, due to your icon's design, made it invisible. This can be a good lesson for you when designing your app icon.

Look what your theme did with the normal Construct 3 icon. For context, review the icons below.

Construct 3 icon:
![image](https://user-images.githubusercontent.com/31282960/235373392-ceddc2ab-bf2f-4ccf-9b79-4eedb752dce5.png)

Your icon:
![image](https://user-images.githubusercontent.com/31282960/235373422-8b47d7b5-103c-468e-89db-5bb57071a8d5.png)

Here is what it looks like with a default Samsung theme:

![image](https://user-images.githubusercontent.com/31282960/235373468-dc76f418-7270-4a19-87f9-9268836269f9.png)

![image](https://user-images.githubusercontent.com/31282960/235373482-18f13f7f-afc2-406b-bbcd-e2e7ea9a0d3c.png)

![image](https://user-images.githubusercontent.com/31282960/235373487-46411a80-3680-4092-95ca-a8a9559a7f04.png)
