### ISSUE TITLE
[Mobile Notification] Android 12, 13. The game is not launched after tap on push notification

### ISSUE THREAD

**Issue by ArtemLanin** [Chadori/construct-master-collection#614]
## Request Type
This is a **Bug Report**.

## Describe the bug
The game is not launched after tap on push notification

## Reproducible .c3p or .capx
[Demo Project.zip](https://github.com/Chadori/Construct-Master-Collection/files/11360115/Demo.Project.zip)

## Steps to Reproduce
1. Install Mobile Notification
2. Build the project
3. Run and click to get any kind of push notification
4. Click on push notification

## Expected behavior
The game/app should be launched but instead the push is just disappear and game/app is not launched

## Screenshots
https://user-images.githubusercontent.com/79050161/235325264-c2262695-6413-460c-a583-23a7c482ad3b.mp4

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
 **CONSTRUCT 3 R336**

## Additional Info
The issue is reproducible on Android 12 (Pixel 3a), On Android 11 it works fine

**Comment by Chadori** [comment]
I can reproduce, I will probably have to update the Cordova plugin. I cannot give an exact ETA, but this is definitely a priority.

**Comment by Chadori** [comment]
I can reproduce, I will probably have to update the Cordova plugin. I cannot give an ETA, but this is definitely a priority.

**Comment by ArtemLanin** [comment]
Just FYI: the same with Android 13 (Pixel 4a)

**Comment by Chadori** [comment]
Fixed in [chadori-mobile-notification@0.0.8](https://www.npmjs.com/package/chadori-mobile-notification), which I've requested for whitelisting in the Construct 3 Build Service. As soon as the Construct Team whitelists the Cordova plugin update, I will release a new Construct 3 plugin update for the [Mobile Notification](https://www.constructcollection.com/documentations/mobile/mobile-notification) plugin as well.

**Comment by Chadori** [comment]
Now fixed in **Mobile Notification** version `2.2.0.0` with demo project version `1.2.0.0`.
