### ISSUE TITLE
Mobile Vibrate. Pattern and all IOS option don't work on iPhones

### ISSUE THREAD

**Issue by ArtemLanin** [Chadori/construct-master-collection#616]
## Request Type
Mobile Vibrate. Pattern and all IOS option don't work on iPhones

## Describe the bug
Only first option "Vibrate" is working on iPhones. Pattern and all IOS option don't work

## Steps to Reproduce
1. Install Mobile Vibrate and open demo project
2. Build demo project with Require Vibrate permission
3. Build Xcode version and run the build on iPhone.
4. Check Every available option

## Expected behavior
All options should work but works only one "Vibrate"
## Screenshots
![photo_2023-05-22_13-54-31](https://github.com/Chadori/Construct-Master-Collection/assets/79050161/fc7ecae6-9827-47cd-9277-b854a75b3a0b)

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Construct 3 Version 
Latest

## Additional Info
Tested on IOS 16, 15 and 13

**Comment by Chadori** [comment]
I believe this was already fixed in [Release 43.0](https://chadori.itch.io/construct-master-collection/devlog/501472/release-43). Make sure you are using the latest version. 

If you have `bundles mode` enabled, make sure to turn if off, save project, restart the Construct 3 editor, reinstall latest plugin, restart Construct 3, and finally reopen your project and save to apply new version. This is a common issue beginners make when enabling bundle mode, so make sure to rule this out.

**Comment by ArtemLanin** [comment]
Thanks, I was on Release 42. Just checked on Release 43 and works fine except (Pattern, Gesture Selection start/end + all from Unofficial API).

About bundles mode, I'm not sure, could you provide details where it can be enabled/disabled so I can check.

Thanks!

**Comment by Chadori** [comment]
Just tested on iPhone XS Max and iPhone 14 Pro Max, everything seems to work fine.

**Comment by Chadori** [comment]
Upon investigation, I think this is related to (https://github.com/Chadori/Construct-Master-Collection/issues/635). I have queued the update for this fix in the upcoming `Release 44`. If you still encounter issues, please let me know and I will reopen this issue.

Thank you.
